[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_multi_airdrop = "DDGa2CL5TNgnL5wBJXdn3RcZugKmcwNzxsZ422os6HYt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/jack/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
